
// fetch(`https://restcountries.com/v3.1/independent?status=true`)
//     .then((response) => {
//         return response.json();
//     })
//     .then((data) => {
//         data.sort((a, b) => {
//             if (a.name.common < b.name.common) {
//                 return -1;
//             }
//             if (a.name.common > b.name.common) {
//                 return 1;
//             }
//             return 0;
//         })

//         console.log(data);
//         console.log(data[0].cca2);

//         // document.getElementById("data").innerHTML = `<img src="https://flagcdn.com/256x192/${data[0].cca2.toLowerCase()}.png">`
//     })
//     .catch((error) => {
//         throw error;
//     });


function loadData() {
    
}